# Generated by Django 5.1.4 on 2024-12-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='passwd',
            new_name='password',
        ),
    ]
